### ISSUE TITLE
Docker + Browser ?

### ISSUE THREAD

**Issue by accforgithubtest** [cpcloud/minesweep-rs#1168]
I am trying to run minesweep-rs via docker, and I am assuming that this would be playable via the browser ?
Since no ports were specified, I assume it will run on the default port 80 ? 

Any other configurations are necessary while running via docker ?

The error I see is -

```
Actions
Error: sweep failed
Caused by:
    0: failed to get stdout in raw mode
    1: Not a tty (os error 25)
Error: sweep failed
Caused by:
    0: failed to get stdout in raw mode
    1: Not a tty (os error 25)
Error: sweep failed
Caused by:
    0: failed to get stdout in raw mode
    1: Not a tty (os error 25)
Error: sweep failed
Caused by:
    0: failed to get stdout in raw mode
    1: Not a tty (os error 25)
Error: sweep failed
```

**Comment by cpcloud** [comment]
How are you running the container?

Just because an application is containerized doesn't mean it can run in the browser.

Couple of things to note:

1. There's no server running in the container, and thus nothing is listening on any port, including port 80.

2. In the README, there's a command:

```
docker run --rm -it ghcr.io/cpcloud/minesweep-rs:latest
```

Those `-it` flags are important. Without both of them, you won't be able to interact with the program running through docker.
